### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer in wm_register_to_atlas_new.py when using U fiber clustering button.

### ISSUE THREAD

**Issue by yunyunjin** [GaoxingZheng/UFA_toolbox#1]
**Description**:
```markdown
### Description
I'm experiencing an error when using the UFA toolbox and clicking the U fiber clustering button. The error message indicates that a `float` object is being interpreted as an integer in the `wm_register_to_atlas_new.py` script.

### Error Message
```
Traceback (most recent call last):
  File "/usr/local/bin/wm_register_to_atlas_new.py", line 375, in <module>
    main()
  File "/usr/local/bin/wm_register_to_atlas_new.py", line 348, in main
    register.iterate()
  File "/usr/local/lib/python3.10/dist-packages/whitematteranalysis/congeal_to_atlas.py", line 111, in iterate
    dirname = f"iteration_{self.total_iterations:05d}_sigma_{self.sigma:05d}"
ValueError: Unknown format code 'd' for object of type 'float'
```

### Additional Context
- This issue occurs with the latest version of `whitematteranalysis` (0.4.0).
- Environment details:
  - Python: 3.10
  - OS: Windows 11 using Ubuntu Docker

### Related Issues
I found a similar issue in [Issue #112](https://github.com/SlicerDMRI/whitematteranalysis/issues/112), which suggested updating to a newer version. However, I am already using the latest version (0.4.0) and the issue persists.

Please take a look and let me know if there's any fix or workaround.

Thank you!
```

**Comment by yunyunjin** [comment]
sovled 👍 

1. congeal_to_atlas.py 
sed -i 's/dirname = f"iteration_{self.total_iterations:05d}_sigma_{self.sigma:05d}"/dirname = f"iteration_{self.total_iterations:05d}_sigma_{self.sigma:05.2f}"/' /usr/local/lib/python3.10/dist-packages/whitematteranalysis/congeal_to_atlas.py

2. congeal_multisubject.py 
sed -i 's/register.process_id_string = f"_subject_{subject_idx:05d}_iteration_{iteration_count:05d}_sigma_{sigma:03d}"/register.process_id_string = f"_subject_{subject_idx:05d}_iteration_{iteration_count:05d}_sigma_{sigma:03.2f}"/' /usr/local/lib/python3.10/dist-packages/whitematteranalysis/congeal_multisubject.py

**Comment by GaoxingZheng** [comment]
Hi, I have submitted the "WMA_Package_Bug_fix.docx" to Github, it will help you! Thank you very much!
