### ISSUE TITLE
Questions on Re-Parcellating WMH, Processing Multiple Subjects, and Extracting Fasciculus in UFA Toolbox

### ISSUE THREAD

**Issue by yunyunjin** [GaoxingZheng/UFA_toolbox#2]
### Description
I have a few questions regarding the use of the UFA toolbox and would appreciate any guidance:

1. How can I re-parcellate WMH areas using a different atlas, such as aparc+aseg?
2. Is there a way to process multiple subjects at once with the UFA toolbox, or do I need to handle each subject individually?
3. How can I extract fasciculus instead of U-fiber using the toolbox? Any tips or resources would be very helpful.

Thank you for your assistance!

**Comment by GaoxingZheng** [comment]
Hi, thank you for your interest in my toolbox. You have suggested some great questions!
1. You may need to carefully read the code of CNS (which was used in my toolbox to extract the WMHs) and you can modify the codes to achieve your goal.
2. Yes, you can write batch processing scripts by combining all the codes in the UFA toolbox and it can handle multi-subject situations.
3. Yes, you can modify the input file in WMA_clustering_SWM.sh and select the whole brain fibers as input and it can result in 74 fiber tracts in both superficial and deep white matter regions.

For more detailed questions, you can contact me by email (zheng_gao_xing@163.com) or follow my Wechat official account "神农造大脑” can leave your message in the chat box.

**Comment by GaoxingZheng** [comment]
> ### Description
> I have a few questions regarding the use of the UFA toolbox and would appreciate any guidance:
> 
> 1. How can I re-parcellate WMH areas using a different atlas, such as aparc+aseg?
> 2. Is there a way to process multiple subjects at once with the UFA toolbox, or do I need to handle each subject individually?
> 3. How can I extract fasciculus instead of U-fiber using the toolbox? Any tips or resources would be very helpful.
> 
> Thank you for your assistance!

**Comment by GaoxingZheng** [comment]
> ### Description
> I have a few questions regarding the use of the UFA toolbox and would appreciate any guidance:
> 
> 1. How can I re-parcellate WMH areas using a different atlas, such as aparc+aseg?
> 2. Is there a way to process multiple subjects at once with the UFA toolbox, or do I need to handle each subject individually?
> 3. How can I extract fasciculus instead of U-fiber using the toolbox? Any tips or resources would be very helpful.
> 
> Thank you for your assistance!

Hi, I have updated the UFA toolbox and now it can extract and quantify the whole brain white matter fibers (including 16 superficial fibers and 58 deep white matter fibers). Maybe you can download the latest UFA toolbox from the baiduNet disk. If you have any other questions, please leave your message. Good luck to you!
